# Generated by Django 6.0 on 2025-12-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='base_unit',
            field=models.CharField(choices=[('kg', 'Kilogramm'), ('l', 'Liter')], default='kg', max_length=2),
        ),
    ]
